# Generated by Django 3.2.3 on 2021-09-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(default='', max_length=150)),
                ('message', models.TextField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
