# Generated by Django 3.2.3 on 2021-09-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name_of_event',
            new_name='Event_name',
        ),
    ]
