# Generated by Django 3.2.3 on 2021-09-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_name_of_event_event_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Football_Event',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Groupname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
