# Generated by Django 3.2.3 on 2021-09-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210905_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bharatanatyam_Event',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Groupsong_Event',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Group_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mime_Event',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Group_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mohiniyattam_Event',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Painting_Event',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Football_Event',
            new_name='Groupdance_Event',
        ),
        migrations.RenameField(
            model_name='groupdance_event',
            old_name='Groupname',
            new_name='Group_name',
        ),
    ]
